# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 22:09
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('second_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='beltapp.User')),
                ('user_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='beltapp.User')),
            ],
        ),
    ]
